// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW-g385o-RT7GE_z-Q0FpMz9P5HR4LUuo',
    appId: '1:821083100323:web:b18bb485a6df1bb5d31b16',
    messagingSenderId: '821083100323',
    projectId: 'sti-sync',
    authDomain: 'sti-sync.firebaseapp.com',
    storageBucket: 'sti-sync.firebasestorage.app',
    measurementId: 'G-51X2P4CQV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqivBtIKfQ1NHenPUSSC9oBksEoTEVaOI',
    appId: '1:821083100323:android:3566177e41fbe333d31b16',
    messagingSenderId: '821083100323',
    projectId: 'sti-sync',
    storageBucket: 'sti-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYpli9ISiN2drZxQcrWtD5OHZtb3ms5DU',
    appId: '1:821083100323:ios:be1089aee2ae3b99d31b16',
    messagingSenderId: '821083100323',
    projectId: 'sti-sync',
    storageBucket: 'sti-sync.firebasestorage.app',
    iosBundleId: 'com.example.stiSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYpli9ISiN2drZxQcrWtD5OHZtb3ms5DU',
    appId: '1:821083100323:ios:be1089aee2ae3b99d31b16',
    messagingSenderId: '821083100323',
    projectId: 'sti-sync',
    storageBucket: 'sti-sync.firebasestorage.app',
    iosBundleId: 'com.example.stiSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW-g385o-RT7GE_z-Q0FpMz9P5HR4LUuo',
    appId: '1:821083100323:web:15c0a1516da739bdd31b16',
    messagingSenderId: '821083100323',
    projectId: 'sti-sync',
    authDomain: 'sti-sync.firebaseapp.com',
    storageBucket: 'sti-sync.firebasestorage.app',
    measurementId: 'G-VN152S154Y',
  );
}
